---

- name: install uwsgi with python2 support
  pacman: name={{ item }} state=installed
  with_items:
    - uwsgi
    - uwsgi-plugin-python2
  tags: uwsgi

- name: create uwsgi conf directory
  file: name=/etc/uwsgi state=directory
        owner={{ uwsgi_user }} group={{ uwsgi_user }} mode=640
  tags: uwsgi

- name: create uwsgi common config
  template: src=common.ini.j2 dest=/etc/uwsgi/common.ini
            owner={{ uwsgi_user }} group={{ uwsgi_user }} mode=640
  tags: uwsgi

- name: install uwsgi services
  pacman: name={{ item.name }} state=installed
  with_items: uwsgi_services
  tags: uwsgi

- name: configure uwsgi services
  template: src=service.ini.j2 dest=/etc/uwsgi/{{ item.name }}.ini
            owner={{ uwsgi_user }} group={{ uwsgi_user }} mode=640
  with_items: uwsgi_services
  tags: uwsgi

- name: enable uwsgi service sockets
  command: /usr/bin/systemctl enable uwsgi@{{ item.name }}.socket
           creates=/etc/systemd/system/sockets.target.wants/uwsgi@{{ item.name }}.socket
  with_items: uwsgi_services
  tags: uwsgi

- name: start uwsgi service sockets
  service: name=uwsgi@{{ item.name }}.socket state=started
  with_items: uwsgi_services
  tags: uwsgi
