---

- hosts: all
  gather_facts: no
  roles:
  - systemd
  - pacman
  - ssh
  - iptables
  - ntp
  - logrotate

- hosts: servers
  gather_facts: no
  roles:
  - dhcp
  - pam

- hosts: wsgiservers
  gather_facts: no
  roles:
  - uwsgi

- hosts: httpservers
  gather_facts: no
  roles:
  - nginx

- hosts: redisservers
  gather_facts: no
  roles:
  - redis

- hosts: postgresqlservers
  gather_facts: no
  roles:
  - postgresql

- hosts: ircclients
  gather_facts: no
  roles:
  - irssi

- hosts: developmentenvironments
  gather_facts: no
  roles:
  - development

- hosts: laptops
  gather_facts: no
  roles:
  - desktop
  - acpid
  - swifer
