---

- hosts: all
  user: root
  gather_facts: no
  roles:
  - archlinux
  - systemd
  - pacman
  - ssh
  - iptables
  - ntp

- hosts: servers
  user: root
  gather_facts: no
  roles:
  - dhcp
  - pam
