---

- hosts: all
  gather_facts: no
  roles:
  - systemd
  - pacman
  - ssh
  - iptables
  - ntp
  - cron
  - logrotate
  - user

- hosts: servers
  gather_facts: no
  roles:
  - dhcp
  - pam

- hosts: wsgiservers
  gather_facts: no
  roles:
  - uwsgi

- hosts: httpservers
  gather_facts: no
  roles:
  - nginx

- hosts: redisservers
  gather_facts: no
  roles:
  - redis

- hosts: postgresqlservers
  gather_facts: no
  roles:
  - postgresql

- hosts: qemuservers
  gather_facts: no
  roles:
  - qemu

- hosts: nfsservers
  gather_facts: no
  roles:
  - nfs

- hosts: ansibleclients
  gather_facts: no
  roles:
  - ansible

- hosts: tarsnapclients
  gather_facts: no
  roles:
  - tarsnap
  - snapback

- hosts: ircclients
  gather_facts: no
  roles:
  - irssi

- hosts: developmentenvironments
  gather_facts: no
  roles:
  - development

- hosts: laptops
  gather_facts: no
  roles:
  - acpid
  - swifer
  - x
  - font
  - vm
  - xdevelopment
  - web
  - media

- hosts: mbp82s
  gather_facts: no
  roles:
  - broadcom-wl
  - gmux
