---

- name: set hostname
  template: src=hostname.j2 dest=/etc/hostname
  notify: update hostname
  tags: systemd

- name: set timezone
  template: src=timezone.j2 dest=/etc/timezone
  notify: update timezone
  tags: systemd
