---

- name: set hostname
  template: src=hostname.j2 dest=/etc/hostname
  notify: update hostname
  tags: systemd

- name: set timezone
  template: src=timezone.j2 dest=/etc/timezone
  notify: update timezone
  tags: systemd

- name: set available locales
  template: src=locale.gen.j2 dest=/etc/locale.gen
  notify: generate locales
  tags: systemd

- name: set default locale
  template: src=locale.conf.j2 dest=/etc/locale.conf
  tags: systemd

- name: persist journal
  file: path=/var/log/journal state=directory
  tags: systemd

- name: configure journald
  template: src=journald.conf.j2 dest=/etc/systemd/journald.conf
  notify: restart journald
  tags: systemd

- name: configure logind
  template: src=journald.conf.j2 dest=/etc/systemd/journald.conf
  notify: restart logind
  tags: systemd
