---

- name: install iptables
  pacman: name=iptables state=installed

- name: configure iptables rules
  template: src=iptables.rules.j2 dest=/etc/iptables/iptables.rules
  notify: reload iptables

- name: start and enable iptables
  service: name=iptables state=started enabled=yes
