---

- name: install acpid and dependencies
  pacman: name={{ item }} state=installed
  with_items:
    - acpid
    - xorg-xset
  tags: acpid

- name: configure acpid
  copy: src=handler.sh dest=/etc/acpi/handler.sh mode=755
  tags: acpid

- name: start and enable acpid
  service: name=acpid state=started enabled=yes
  tags: acpid
