---

- name: install nfs utils
  pacman: name=nfs-utils state=installed
  tags: nfs

- name: create nfs export root
  file: name={{ nfs_exports.root }} state=directory
  when: "'nfsservers' in group_names"
  tags: nfs

- name: create bind mounts for nfs exports
  mount: name={{ nfs_exports.root }}/{{ item.target }} src={{ item.source }}
         fstype=none opts=bind state=mounted
  with_items: nfs_exports.mounts
  when: "'nfsservers' in group_names"
  tags: nfs

- name: configure nfs exports
  template: src=exports.j2 dest=/etc/exports
  notify: reload exportfs
  when: "'nfsservers' in group_names"
  tags: nfs

- name: create mounts on nfs client
  mount: name={{ item.target }} src={{ item.source }}
         fstype=nfs4 opts={{ item.options }} state=present
  with_items: nfs_mounts
  when: "'nfsclients' in group_names"

  tags: nfs
- name: start and enable nfs server services
  service: name={{ item }} state=started enabled=yes
  with_items:
    - rpc-idmapd
    - rpc-mountd
  when: "'nfsservers' in group_names"
  tags: nfs
