---

- name: install dhcpcd
  pacman: name=dhcpcd state=installed
  tags: dhcp

- name: start and enable dhcpcd service
  service: name=dhcpcd@{{ dhcp_interface }} state=running enabled=yes
  tags: dhcp
