---

- name: pacman config
  template: src=pacman.conf.j2 dest=/etc/pacman.conf
  tags:
    - pacman

- name: pacman mirrors
  template: src=mirrorlist.j2 dest=/etc/pacman.d/mirrorlist
  tags:
    - pacman
