---

- name: install base development environment
  pacman: name={{ item }} state=installed
  with_items:
    - bash-completion
    - vim
    - git
    - mercurial
    - tig
    - hub
    - the_silver_searcher
    - inotify-tools
    - cloc
    - gettext
    - bc
  tags: development

- name: install c development environment
  pacman: name={{ item }} state=installed
  with_items:
    - valgrind
    - gdb
  tags: development
