---

- name: install development environment
  pacman: name={{ item }} state=installed
  with_items:
    - bash-completion
    - vim
    - git
    - tig
    - hub
    - the_silver_searcher
    - bc
  tags: development
