---

- name: install base development environment
  pacman: name={{ item }} state=installed
  with_items:
    - bash-completion
    - vim
    - git
    - mercurial
    - tig
    - hub
    - the_silver_searcher
    - inotify-tools
    - cloc
    - gettext
    - bc
  tags: development

- name: install c development environment
  pacman: name={{ item }} state=installed
  with_items:
    - valgrind
    - gdb
  tags: development

- name: install python development environment
  pacman: name={{ item }} state=installed
  with_items:
    - python2
    - python2-virtualenv
    - python2-pyflakes
  tags: development

- name: make python2 default python
  file: src=/usr/bin/{{ item }}2 dest=/usr/bin/{{ item }} state=link
  with_items:
    - python
    - virtualenv
  tags: development
