---

- name: install base development environment
  pacman: name={{ item }} state=installed
  with_items:
    - bash-completion
    - vim
    - tmux
    - git
    - mercurial
    - tig
    - hub
    - the_silver_searcher
    - inotify-tools
    - cloc
    - gettext
    - bc
  tags: development

- name: install analysis applications 
  pacman: name={{ item }} state=installed
  with_items:
    - htop
    - lsof
    - psm
    - sysstat
    - iotop
    - perf
    - wrk
  tags: development

- name: install c development environment
  pacman: name={{ item }} state=installed
  with_items:
    - valgrind
    - gdb
  tags: development

- name: install python development environment
  pacman: name={{ item }} state=installed
  with_items:
    - python2
    - python2-virtualenv
    - python2-pyflakes
  tags: development

- name: make python2 default python
  file: src=/usr/bin/{{ item }}2 dest=/usr/bin/{{ item }} state=link
  with_items:
    - python
    - virtualenv
  tags: development

- name: install js development environment
  pacman: name={{ item }} state=installed
  with_items:
    - nodejs
    - n
  tags: development

- name: install go development environment
  pacman: name={{ item }} state=installed
  with_items:
    - go
    - johnny-deps
  tags: development

- name: install packaging environment
  pacman: name={{ item }} state=installed
  with_items:
    - autoconf
    - automake
    - binutils
    - bison
    - fakeroot
    - flex
    - gcc
    - libtool
    - m4
    - make
    - patch
    - pkg-config
  tags: development

- name: configure packaging environment
  template: src=makepkg.conf.j2 dest=/etc/makepkg.conf
  tags: development
